### ISSUE TITLE
No module named 'tetra3'

### ISSUE THREAD

**Issue by sajmons** [adambaskerville/AstroPitography#3] opened 2022-05-26 09:19 UTC
After running command: python3 AstroPitography.py

I get this error:

Traceback (most recent call last):
  File "AstroPitography.py", line 55, in <module>
    from tetra3 import Tetra3
ModuleNotFoundError: No module named 'tetra3'

I tried to install tetra3 module with command:

pip3 install tetra3

And I get this:

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting tetra3
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/tetra3/

Please help!

**Comment by adambaskerville** [comment] 2022-05-27 07:45
Hey there, thank you for the feedback. I plan to make the installation a lot easier in the coming months by designing a conda environment which will handle all the installation (just struggling to find time at the moment). Till then take a look at this page:

https://tetra3.readthedocs.io/en/latest/installation.html

tetra3 is not available on PIP/PyPI (the Python Package Index). Instead you need to get the software repository from GitHub and place it in the directory where you wish to use it. The page above describes how to install it. In a future release all of the relevant files will be included in this repo to make installation easier.

**Closed** 2024-02-24 01:43 UTC
